// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Linux基本操作',
      items: ['Linux基本操作/unix','Linux基本操作/基本コマンド','Linux基本操作/bash',
        'Linux基本操作/vi','Linux基本操作/awk','Linux基本操作/apt'],
    },
    {
      type: 'category',
      label: 'wsl',
      items: ['wsl/wsl概要','wsl/wslインストール','wsl/sshdサーバ起動'],
    },
  ],
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
